name: "CI"
on:
  push:
    branches:
      - master

jobs:

  lint:
    environment: Production
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout source
      uses: actions/checkout@v1

    - name: run protolint
      uses: plexsystems/protolint-action@v0.2.0

  update-docs:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - name: Update Docs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Update protobufs"
          repo: meshtastic/meshtastic
          token: ${{ secrets.ACCESS_TOKEN }}
