name: "CI"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: checkout source
      uses: actions/checkout@v1

    - name: run protolint
      uses: plexsystems/protolint-action@v0.2.0
      with:
        configDirectory: .
